#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern "C" void _ALU_reg(void);
extern "C" void _CoreNEURONArtificialCell_reg(void);
extern "C" void _DetAMPANMDA_reg(void);
extern "C" void _DetGABAAB_reg(void);
extern "C" void _GluSynapse_reg(void);
extern "C" void _HDF5reader_reg(void);
extern "C" void _Im_ms_reg(void);
extern "C" void _NO_reg(void);
extern "C" void _ProbAMPANMDA_EMS_reg(void);
extern "C" void _ProbGABAAB_EMS_reg(void);
extern "C" void _SonataReportHelper_reg(void);
extern "C" void _SonataReports_reg(void);
extern "C" void _SpikeWriter_reg(void);
extern "C" void _SynapseReader_reg(void);
extern "C" void _TTXDynamicsSwitch_reg(void);
extern "C" void _VecStim_reg(void);
extern "C" void _bk_ch_reg(void);
extern "C" void _bk_fs_reg(void);
extern "C" void _bk_ms_reg(void);
extern "C" void _ca_ch_reg(void);
extern "C" void _cacumm_reg(void);
extern "C" void _cacummb_reg(void);
extern "C" void _cadyn_fs_reg(void);
extern "C" void _cadyn_ms_reg(void);
extern "C" void _cagk_reg(void);
extern "C" void _cal12_ms_reg(void);
extern "C" void _cal13_ms_reg(void);
extern "C" void _cal2_reg(void);
extern "C" void _cal_ch_reg(void);
extern "C" void _caldyn_ms_reg(void);
extern "C" void _can2_reg(void);
extern "C" void _can_fs_reg(void);
extern "C" void _can_ms_reg(void);
extern "C" void _cap_ch_reg(void);
extern "C" void _caq_fs_reg(void);
extern "C" void _caq_ms_reg(void);
extern "C" void _car_fs_reg(void);
extern "C" void _car_ms_reg(void);
extern "C" void _cat_reg(void);
extern "C" void _cat32_ms_reg(void);
extern "C" void _cat33_ms_reg(void);
extern "C" void _gap_reg(void);
extern "C" void _h_reg(void);
extern "C" void _hcn12_ch_reg(void);
extern "C" void _hd_lts_reg(void);
extern "C" void _im_lts_reg(void);
extern "C" void _it_lts_reg(void);
extern "C" void _kadist_reg(void);
extern "C" void _kaf_fs_reg(void);
extern "C" void _kaf_lts_reg(void);
extern "C" void _kaf_ms_reg(void);
extern "C" void _kaprox_reg(void);
extern "C" void _kas_fs_reg(void);
extern "C" void _kas_ms_reg(void);
extern "C" void _kca_reg(void);
extern "C" void _kcnq_ch_reg(void);
extern "C" void _kd_reg(void);
extern "C" void _kd2_reg(void);
extern "C" void _kdb_reg(void);
extern "C" void _kdb_lts_reg(void);
extern "C" void _kdr_fs_reg(void);
extern "C" void _kdr_lts_reg(void);
extern "C" void _kdr_ms_reg(void);
extern "C" void _kdrb_lts_reg(void);
extern "C" void _kdrbca1_reg(void);
extern "C" void _kdrca1_reg(void);
extern "C" void _kir23_ch_reg(void);
extern "C" void _kir23_lts_reg(void);
extern "C" void _kir2_ch_reg(void);
extern "C" void _kir_fs_reg(void);
extern "C" void _kir_ms_reg(void);
extern "C" void _km_reg(void);
extern "C" void _kmb_reg(void);
extern "C" void _kv2_ch_reg(void);
extern "C" void _kv4_ch_reg(void);
extern "C" void _lookupTableV2_reg(void);
extern "C" void _na2_ch_reg(void);
extern "C" void _na3_lts_reg(void);
extern "C" void _na3n_reg(void);
extern "C" void _na_ch_reg(void);
extern "C" void _naf_fs_reg(void);
extern "C" void _naf_lts_reg(void);
extern "C" void _naf_ms_reg(void);
extern "C" void _naxn_reg(void);
extern "C" void _netstim_inhpoisson_reg(void);
extern "C" void _par_ggap_reg(void);
extern "C" void _sk_ch_reg(void);
extern "C" void _sk_fs_reg(void);
extern "C" void _sk_ms_reg(void);
extern "C" void _tmgabaa_reg(void);
extern "C" void _tmglut_reg(void);
extern "C" void _tmglut_M1RH_D1_reg(void);
extern "C" void _tmglut_double_reg(void);
extern "C" void _vecevent_reg(void);

extern "C" void modl_reg() {
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");
    fprintf(stderr, " \"hippocampus/mod//ALU.mod\"");
    fprintf(stderr, " \"hippocampus/mod//CoreNEURONArtificialCell.mod\"");
    fprintf(stderr, " \"hippocampus/mod//DetAMPANMDA.mod\"");
    fprintf(stderr, " \"hippocampus/mod//DetGABAAB.mod\"");
    fprintf(stderr, " \"hippocampus/mod//GluSynapse.mod\"");
    fprintf(stderr, " \"hippocampus/mod//HDF5reader.mod\"");
    fprintf(stderr, " \"hippocampus/mod//Im_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//NO.mod\"");
    fprintf(stderr, " \"hippocampus/mod//ProbAMPANMDA_EMS.mod\"");
    fprintf(stderr, " \"hippocampus/mod//ProbGABAAB_EMS.mod\"");
    fprintf(stderr, " \"hippocampus/mod//SonataReportHelper.mod\"");
    fprintf(stderr, " \"hippocampus/mod//SonataReports.mod\"");
    fprintf(stderr, " \"hippocampus/mod//SpikeWriter.mod\"");
    fprintf(stderr, " \"hippocampus/mod//SynapseReader.mod\"");
    fprintf(stderr, " \"hippocampus/mod//TTXDynamicsSwitch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//VecStim.mod\"");
    fprintf(stderr, " \"hippocampus/mod//bk_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//bk_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//bk_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//ca_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cacumm.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cacummb.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cadyn_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cadyn_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cagk.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cal12_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cal13_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cal2.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cal_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//caldyn_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//can2.mod\"");
    fprintf(stderr, " \"hippocampus/mod//can_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//can_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cap_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//caq_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//caq_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//car_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//car_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cat.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cat32_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//cat33_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//gap.mod\"");
    fprintf(stderr, " \"hippocampus/mod//h.mod\"");
    fprintf(stderr, " \"hippocampus/mod//hcn12_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//hd_lts.mod\"");
    fprintf(stderr, " \"hippocampus/mod//im_lts.mod\"");
    fprintf(stderr, " \"hippocampus/mod//it_lts.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kadist.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kaf_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kaf_lts.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kaf_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kaprox.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kas_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kas_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kca.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kcnq_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kd.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kd2.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kdb.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kdb_lts.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kdr_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kdr_lts.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kdr_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kdrb_lts.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kdrbca1.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kdrca1.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kir23_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kir23_lts.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kir2_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kir_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kir_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//km.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kmb.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kv2_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//kv4_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//lookupTableV2.mod\"");
    fprintf(stderr, " \"hippocampus/mod//na2_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//na3_lts.mod\"");
    fprintf(stderr, " \"hippocampus/mod//na3n.mod\"");
    fprintf(stderr, " \"hippocampus/mod//na_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//naf_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//naf_lts.mod\"");
    fprintf(stderr, " \"hippocampus/mod//naf_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//naxn.mod\"");
    fprintf(stderr, " \"hippocampus/mod//netstim_inhpoisson.mod\"");
    fprintf(stderr, " \"hippocampus/mod//par_ggap.mod\"");
    fprintf(stderr, " \"hippocampus/mod//sk_ch.mod\"");
    fprintf(stderr, " \"hippocampus/mod//sk_fs.mod\"");
    fprintf(stderr, " \"hippocampus/mod//sk_ms.mod\"");
    fprintf(stderr, " \"hippocampus/mod//tmgabaa.mod\"");
    fprintf(stderr, " \"hippocampus/mod//tmglut.mod\"");
    fprintf(stderr, " \"hippocampus/mod//tmglut_M1RH_D1.mod\"");
    fprintf(stderr, " \"hippocampus/mod//tmglut_double.mod\"");
    fprintf(stderr, " \"hippocampus/mod//vecevent.mod\"");
    fprintf(stderr, "\n");
  }
  _ALU_reg();
  _CoreNEURONArtificialCell_reg();
  _DetAMPANMDA_reg();
  _DetGABAAB_reg();
  _GluSynapse_reg();
  _HDF5reader_reg();
  _Im_ms_reg();
  _NO_reg();
  _ProbAMPANMDA_EMS_reg();
  _ProbGABAAB_EMS_reg();
  _SonataReportHelper_reg();
  _SonataReports_reg();
  _SpikeWriter_reg();
  _SynapseReader_reg();
  _TTXDynamicsSwitch_reg();
  _VecStim_reg();
  _bk_ch_reg();
  _bk_fs_reg();
  _bk_ms_reg();
  _ca_ch_reg();
  _cacumm_reg();
  _cacummb_reg();
  _cadyn_fs_reg();
  _cadyn_ms_reg();
  _cagk_reg();
  _cal12_ms_reg();
  _cal13_ms_reg();
  _cal2_reg();
  _cal_ch_reg();
  _caldyn_ms_reg();
  _can2_reg();
  _can_fs_reg();
  _can_ms_reg();
  _cap_ch_reg();
  _caq_fs_reg();
  _caq_ms_reg();
  _car_fs_reg();
  _car_ms_reg();
  _cat_reg();
  _cat32_ms_reg();
  _cat33_ms_reg();
  _gap_reg();
  _h_reg();
  _hcn12_ch_reg();
  _hd_lts_reg();
  _im_lts_reg();
  _it_lts_reg();
  _kadist_reg();
  _kaf_fs_reg();
  _kaf_lts_reg();
  _kaf_ms_reg();
  _kaprox_reg();
  _kas_fs_reg();
  _kas_ms_reg();
  _kca_reg();
  _kcnq_ch_reg();
  _kd_reg();
  _kd2_reg();
  _kdb_reg();
  _kdb_lts_reg();
  _kdr_fs_reg();
  _kdr_lts_reg();
  _kdr_ms_reg();
  _kdrb_lts_reg();
  _kdrbca1_reg();
  _kdrca1_reg();
  _kir23_ch_reg();
  _kir23_lts_reg();
  _kir2_ch_reg();
  _kir_fs_reg();
  _kir_ms_reg();
  _km_reg();
  _kmb_reg();
  _kv2_ch_reg();
  _kv4_ch_reg();
  _lookupTableV2_reg();
  _na2_ch_reg();
  _na3_lts_reg();
  _na3n_reg();
  _na_ch_reg();
  _naf_fs_reg();
  _naf_lts_reg();
  _naf_ms_reg();
  _naxn_reg();
  _netstim_inhpoisson_reg();
  _par_ggap_reg();
  _sk_ch_reg();
  _sk_fs_reg();
  _sk_ms_reg();
  _tmgabaa_reg();
  _tmglut_reg();
  _tmglut_M1RH_D1_reg();
  _tmglut_double_reg();
  _vecevent_reg();
}
