#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern "C" void _ALU_reg(void);
extern "C" void _CoreNEURONArtificialCell_reg(void);
extern "C" void _GRC_CA_reg(void);
extern "C" void _GRC_KM_reg(void);
extern "C" void _Gfluct_reg(void);
extern "C" void _GluSynapse_reg(void);
extern "C" void _HDF5reader_reg(void);
extern "C" void _Kca11_reg(void);
extern "C" void _Kca22_reg(void);
extern "C" void _Kir23_reg(void);
extern "C" void _Kv11_reg(void);
extern "C" void _Kv15_reg(void);
extern "C" void _Kv22_reg(void);
extern "C" void _Kv34_reg(void);
extern "C" void _Kv43_reg(void);
extern "C" void _Leak_reg(void);
extern "C" void _ProbAMPANMDA_EMS_reg(void);
extern "C" void _ProbGABAAB_EMS_reg(void);
extern "C" void _SonataReportHelper_reg(void);
extern "C" void _SonataReports_reg(void);
extern "C" void _SpikeWriter_reg(void);
extern "C" void _SynapseReader_reg(void);
extern "C" void _ThreshDetect_reg(void);
extern "C" void _VecStim_reg(void);
extern "C" void _ampanmda_reg(void);
extern "C" void _distrt_reg(void);
extern "C" void _fi_reg(void);
extern "C" void _fi_stdp_reg(void);
extern "C" void _gap_reg(void);
extern "C" void _kamt_reg(void);
extern "C" void _kdrmt_reg(void);
extern "C" void _ks_reg(void);
extern "C" void _lookupTableV2_reg(void);
extern "C" void _naxn_reg(void);
extern "C" void _netstim_inhpoisson_reg(void);
extern "C" void _orn_reg(void);
extern "C" void _ostimhelper_reg(void);

extern "C" void modl_reg() {
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");
    fprintf(stderr, " \"cerebellum/mod//ALU.mod\"");
    fprintf(stderr, " \"cerebellum/mod//CoreNEURONArtificialCell.mod\"");
    fprintf(stderr, " \"cerebellum/mod//GRC_CA.mod\"");
    fprintf(stderr, " \"cerebellum/mod//GRC_KM.mod\"");
    fprintf(stderr, " \"cerebellum/mod//Gfluct.mod\"");
    fprintf(stderr, " \"cerebellum/mod//GluSynapse.mod\"");
    fprintf(stderr, " \"cerebellum/mod//HDF5reader.mod\"");
    fprintf(stderr, " \"cerebellum/mod//Kca11.mod\"");
    fprintf(stderr, " \"cerebellum/mod//Kca22.mod\"");
    fprintf(stderr, " \"cerebellum/mod//Kir23.mod\"");
    fprintf(stderr, " \"cerebellum/mod//Kv11.mod\"");
    fprintf(stderr, " \"cerebellum/mod//Kv15.mod\"");
    fprintf(stderr, " \"cerebellum/mod//Kv22.mod\"");
    fprintf(stderr, " \"cerebellum/mod//Kv34.mod\"");
    fprintf(stderr, " \"cerebellum/mod//Kv43.mod\"");
    fprintf(stderr, " \"cerebellum/mod//Leak.mod\"");
    fprintf(stderr, " \"cerebellum/mod//ProbAMPANMDA_EMS.mod\"");
    fprintf(stderr, " \"cerebellum/mod//ProbGABAAB_EMS.mod\"");
    fprintf(stderr, " \"cerebellum/mod//SonataReportHelper.mod\"");
    fprintf(stderr, " \"cerebellum/mod//SonataReports.mod\"");
    fprintf(stderr, " \"cerebellum/mod//SpikeWriter.mod\"");
    fprintf(stderr, " \"cerebellum/mod//SynapseReader.mod\"");
    fprintf(stderr, " \"cerebellum/mod//ThreshDetect.mod\"");
    fprintf(stderr, " \"cerebellum/mod//VecStim.mod\"");
    fprintf(stderr, " \"cerebellum/mod//ampanmda.mod\"");
    fprintf(stderr, " \"cerebellum/mod//distrt.mod\"");
    fprintf(stderr, " \"cerebellum/mod//fi.mod\"");
    fprintf(stderr, " \"cerebellum/mod//fi_stdp.mod\"");
    fprintf(stderr, " \"cerebellum/mod//gap.mod\"");
    fprintf(stderr, " \"cerebellum/mod//kamt.mod\"");
    fprintf(stderr, " \"cerebellum/mod//kdrmt.mod\"");
    fprintf(stderr, " \"cerebellum/mod//ks.mod\"");
    fprintf(stderr, " \"cerebellum/mod//lookupTableV2.mod\"");
    fprintf(stderr, " \"cerebellum/mod//naxn.mod\"");
    fprintf(stderr, " \"cerebellum/mod//netstim_inhpoisson.mod\"");
    fprintf(stderr, " \"cerebellum/mod//orn.mod\"");
    fprintf(stderr, " \"cerebellum/mod//ostimhelper.mod\"");
    fprintf(stderr, "\n");
  }
  _ALU_reg();
  _CoreNEURONArtificialCell_reg();
  _GRC_CA_reg();
  _GRC_KM_reg();
  _Gfluct_reg();
  _GluSynapse_reg();
  _HDF5reader_reg();
  _Kca11_reg();
  _Kca22_reg();
  _Kir23_reg();
  _Kv11_reg();
  _Kv15_reg();
  _Kv22_reg();
  _Kv34_reg();
  _Kv43_reg();
  _Leak_reg();
  _ProbAMPANMDA_EMS_reg();
  _ProbGABAAB_EMS_reg();
  _SonataReportHelper_reg();
  _SonataReports_reg();
  _SpikeWriter_reg();
  _SynapseReader_reg();
  _ThreshDetect_reg();
  _VecStim_reg();
  _ampanmda_reg();
  _distrt_reg();
  _fi_reg();
  _fi_stdp_reg();
  _gap_reg();
  _kamt_reg();
  _kdrmt_reg();
  _ks_reg();
  _lookupTableV2_reg();
  _naxn_reg();
  _netstim_inhpoisson_reg();
  _orn_reg();
  _ostimhelper_reg();
}
